package com.kentoes.eo.enums;

public enum EJenisSk {
    NULL, SK_KENAIKAN_PANGKAT_GOLONGAN,
    SK_CAPEG, SK_PEGAWAI_TETAP, SK_JABATAN,
    SK_MUTASI, SK_PENSIUN,
    SK_LAINNYA, SK_PENYESUAIAN_GAJI,
    SK_KENAIKAN_GAJI_BERKALA
}
